marketstack:
  key: "YOUR_MARKETSTACK_KEY"
  stocks:
    - AAPL
    - MSFT

yahoo:
  stocks:
    - GOOG

fixer:
  key: "YOUR_FIXER_KEY"
  pairs:
    - { from: "EUR", to: "USD" }
    - { from: "GBP", to: "USD" }

ledger:
   price_db: "/tmp/prices.db"

pushover:
  config:
    token: PUSHOVER_APP_TOKEN
    recipient: PUSHOVER_RECIPIENT_TOKEN
  notify:
    - { stock: "GOOG", price: 450 }
  notify_currency:
    - { from: "EUR", to: "USD", price: 1.13, when: "below" }
